export const Fields =[
    { value: "uxdesign", label: "User Experience (UX) Design" },
{ value: "dataengineering", label: "Data Engineering" },
{ value: "softwareengineering", label: "Software Engineering" },
{ value: "computervision", label: "Computer Vision" },
{ value: "nlp", label: "Natural Language Processing (NLP)" },
{ value: "embeddedsystems", label: "Embedded Systems Design" },
{ value: "cybersecurityanalysis", label: "Cybersecurity Analysis" },
{ value: "networksecurity", label: "Network Security" },
{ value: "devopsengineering", label: "DevOps Engineering" },
{ value: "agileprojectmanagement", label: "Agile Project Management" },
{ value: "softwaretesting", label: "Software Testing" },
{ value: "qa", label: "Quality Assurance (QA)" },
{ value: "uidevelopment", label: "User Interface (UI) Development" },
{ value: "backendwebdev", label: "Back-End Development for Web" },
{ value: "frontendwebdev", label: "Front-End Development for Web" },
{ value: "apidevelopment", label: "API Development" },
{ value: "websecurity", label: "Web Security" },
{ value: "cloudsecurity", label: "Cloud Security" },
{ value: "itinfrastructuremanagement", label: "IT Infrastructure Management" },
{ value: "businessintelligence", label: "Business Intelligence (BI)" },
{ value: "datawarehousing", label: "Data Warehousing" },
{ value: "datavisualization", label: "Data Visualization" },
{ value: "bigdataanalytics", label: "Big Data Analytics" },
{ value: "blockchaindevelopment", label: "Blockchain Development" },
{ value: "rpa", label: "Robotic Process Automation (RPA)" },
{ value: "machinelearningengineering", label: "Machine Learning Engineering" },
{ value: "aiengineering", label: "Artificial Intelligence Engineering" },
{ value: "iotsecurity", label: "Internet of Things (IoT) Security" },
{ value: "ethicalhacking", label: "Ethical Hacking" },
{ value: "digitalforensics", label: "Digital Forensics" },
{ value: "cloudarchitecture", label: "Cloud Architecture" },
{ value: "systemadministration", label: "System Administration" },
{ value: "networkadministration", label: "Network Administration" },
{ value: "virtualization", label: "Virtualization" },
{ value: "softwaredesign", label: "Software Design" },
{ value: "databaseadministration", label: "Database Administration" },
{ value: "softwarearchitecture", label: "Software Architecture" },
{ value: "technicalsupport", label: "Technical Support" },
{ value: "softwareproductmanagement", label: "Software Product Management" },
{ value: "fullstackwebdev", label: "Full Stack Web Development (combines Front-End and Back-End)" },
{ value: "mobileappdev", label: "Mobile App Development (combines Web and Mobile)" },
{ value: "datascienceml", label: "Data Science and Machine Learning" },
{ value: "aiandrobotics", label: "Artificial Intelligence and Robotics" },
{ value: "webdevdevops", label: "Web Development and DevOps" },
{ value: "cloudandsecurity", label: "Cloud Computing and Security" },
{ value: "blockchainsecurity", label: "Blockchain Technology and Security" },
{ value: "iotandml", label: "Internet of Things (IoT) and Machine Learning" },
{ value: "vrardev", label: "Virtual Reality (VR) and Augmented Reality (AR) Development" },
{ value: "mobileuiuxdesign", label: "UI/UX Design for Mobile Apps" },
{ value: "devopsagile", label: "DevOps and Agile Methodologies" },
{ value: "infrastructureautomation", label: "Infrastructure Automation and Cloud Management" },
{ value: "sdt", label: "Software Development and Testing (SDT)" },
{ value: "webapplicationsecurity", label: "Web Application Security Testing" },
{ value: "networksecurityadmin", label: "Network Security and Administration" },
{ value: "mlnlp", label: "Machine Learning and Natural Language Processing (NLP)" },
{ value: "datasciencebi", label: "Data Science and Business Intelligence (BI)" },
{ value: "cloudnativedev", label: "Cloud-Native Development" },
{ value: "serverlessdev", label: "Serverless Architecture and Development" },
{ value: "apidesign", label: "API Design and Development" },
{ value: "graphqldev", label: "GraphQL API Development" },
{ value: "restfulapi", label: "RESTful API Development" },
{ value: "oauthjwt", label: "OAuth and JWT Authentication" },
{ value: "sdlcmanagement", label: "Software Development Lifecycle (SDLC) Management" },
{ value: "itsm", label: "IT Service Management (ITSM)" },
{ value: "cloudcostoptimization", label: "Cloud Cost Optimization" },
{ value: "infrastructureascode", label: "Infrastructure as Code (IaC)" },
{ value: "disasterrecovery", label: "Disaster Recovery and Business Continuity" },
{ value: "ecommercewebdev", label: "Web Development for E-commerce Applications" },
{ value: "arvrmobileappdev", label: "Mobile App Development for AR/VR Experiences" },
{ value: "healthcaredatacience", label: "Data Science for Healthcare Applications" },
{ value: "ainlp", label: "Artificial Intelligence for Natural Language Processing (NLP) Applications" },
{ value: "computervisionml", label: "Machine Learning for Computer Vision Applications" },
{ value: "criticalinfrastructuresecurity", label: "Cybersecurity for Critical Infrastructure" },
{ value: "mediastreamingcloud", label: "Cloud Computing for Media Streaming Services" },
{ value: "blockchainsupplychain", label: "Blockchain Technology for Supply Chain Management" },
{ value: "manufacturingrobotics", label: "Robotics for Automation in Manufacturing" },
{ value: "accessibilityuiuxdesign", label: "UI/UX Design for Accessibility" },
{ value: "devopsci", label: "DevOps for Continuous Integration and Continuous Delivery (CI/CD)" },
{ value: "agileprojectmanagementstartup", label: "Agile Project Management for Startups" },
{ value: "softwaretestingautomation", label: "Software Testing for Automation" },
{ value: "nosqldatabaseadministration", label: "Database Administration for NoSQL Databases" },
{ value: "sdnnetworkadministration", label: "Network Administration for SDN (Software-Defined Networking)" },
{ value: "quantumcomputing", label: "Quantum Computing" },
{ value: "edgecomputing", label: "Edge Computing" },
{ value: "lowcodenocodedev", label: "Low-code/No-code Development" },
{ value: "generativeai", label: "Generative AI" },
{ value: "explainableai", label: "Explainable AI (XAI)" },
{ value: "responsibleai", label: "Responsible AI" },
{ value: "web3development", label: "Web3 Development" },
{ value: "metaversedevelopment", label: "Metaverse Development" },
{ value: "metaversecybersecurity", label: "Cybersecurity for the Metaverse" },
{ value: "gamedesign", label: "Game Design" },
{ value: "gamedevelopment", label: "Game Development" },
{ value: "gameart", label: "Game Art" },
{ value: "gameanimation", label: "Game Animation" },
{ value: "gameaudio", label: "Game Audio Design" },
{ value: "gameuiux", label: "Game UI/UX Design" },
{ value: "3dmodeling", label: "3D Modeling" },
{ value: "3danimation", label: "3D Animation" },
{ value: "vfx", label: "Visual Effects (VFX)" },
{ value: "motiongraphics", label: "Motion Graphics" },
{ value: "uxresearch", label: "UX Research" },
{ value: "informationarchitecture", label: "Information Architecture (IA)" },
{ value: "interactiondesign", label: "Interaction Design" },
{ value: "usabilitytesting", label: "Usability Testing" },
{ value: "contentstrategy", label: "Content Strategy" },
{ value: "contentcreation", label: "Content Creation" },
{ value: "copywriting", label: "Copywriting" },
{ value: "technicalwriting", label: "Technical Writing" },
{ value: "searchengineoptimization", label: "Search Engine Optimization (SEO)" },
{ value: "searchenginemarketing", label: "Search Engine Marketing (SEM)" },
{ value: "socialmediamarketing", label: "Social Media Marketing (SMM)" },
{ value: "payperclick", label: "Pay-Per-Click (PPC) Advertising" },
{ value: "conversionrateoptimization", label: "Conversion Rate Optimization (CRO)" },
{ value: "marketingautomation", label: "Marketing Automation" },
{ value: "projectmanagement", label: "Project Management" },
{ value: "productmanagement", label: "Product Management" },
{ value: "programmanagement", label: "Program Management" },
{ value: "businessanalysis", label: "Business Analysis" },
{ value: "businessdevelopment", label: "Business Development" },
{ value: "sales", label: "Sales" },
{ value: "accountmanagement", label: "Account Management" },
{ value: "customerrelationshipmanagement", label: "Customer Relationship Management (CRM)" },
{ value: "datagovernance", label: "Data Governance" },
{ value: "dataprivacy", label: "Data Privacy" },
{ value: "datasafety", label: "Data Security" },
{ value: "ethicalai", label: "Ethical AI (additional entry)" },  // Added for clarity
{ value: "aibias", label: "AI Bias Detection and Mitigation" },
{ value: "responsibleinnovation", label: "Responsible Innovation" },
{ value: "emergingtechnologies", label: "Emerging Technologies (general category)" }, // Added for flexibility
{ value: "fintech", label: "Financial Technology (FinTech)" },
{ value: "healthtech", label: "Healthcare Technology (HealthTech)" },
{ value: "edtech", label: "Education Technology (EdTech)" },
{ value: "legaltech", label: "Legal Technology (LegalTech)" },
{ value: "agritech", label: "Agricultural Technology (AgTech)" },
{ value: "iotsecurity", label: "Internet of Things (IoT) Security (additional entry)" }, // Added for clarity
{ value: "embeddedsecurity", label: "Embedded Systems Security" },
{ value: "cloudsecurityarchitect", label: "Cloud Security Architect" },
{ value: "networksecurityarchitect", label: "Network Security Architect" },
{ value: "securityoperationscenter", label: "Security Operations Center (SOC)" },
{ value: "incidentresponse", label: "Incident Response" },
{ value: "penetrationtesting", label: "Penetration Testing (Pen Testing)" },
{ value: "vulnerabilitymanagement", label: "Vulnerability Management" },
{ value: "blockchainengineering", label: "Blockchain Engineering (additional entry)" }, // Added for clarity
{ value: "smartcontracts", label: "Smart Contracts Development" },
{ value: "cryptography", label: "Cryptography" },
{ value: "cybersecuritylaw", label: "Cybersecurity Law" },
{ value: "cyberwarfare", label: "Cyber Warfare (defensive)" },
{ value: "digitalforensicsinvestigation", label: "Digital Forensics Investigation" },
{ value: "web", label: "Web Development" },
  { value: "mobile", label: "Mobile Development" },
  { value: "data", label: "Data Science" },
  { value: "ai", label: "Artificial Intelligence" },
  { value: "ml", label: "Machine Learning" },
  { value: "cloud", label: "Cloud Computing" },
  { value: "security", label: "Cyber Security" },
  { value: "networking", label: "Networking" },
  { value: "game", label: "Game Development" },
  { value: "iot", label: "Internet of Things" },
  { value: "vr", label: "Virtual Reality" },
  { value: "ar", label: "Augmented Reality" },
  { value: "blockchain", label: "Blockchain Technology" },
  { value: "bioinformatics", label: "Bioinformatics" },
  { value: "robotics", label: "Robotics" },
  { value: "embedded", label: "Embedded Systems" },
  { value: "uiux", label: "UI/UX Design" },
  { value: "database", label: "Database Management" },
  { value: "frontend", label: "Frontend Development" },
  { value: "backend", label: "Backend Development" },
  { value: "fullstack", label: "Full Stack Development" },
  { value: "devops", label: "DevOps" },
  { value: "agile", label: "Agile Methodologies" },
  { value: "scrum", label: "Scrum Framework" },
  { value: "kanban", label: "Kanban Methodology" },
  { value: "git", label: "Git Version Control" },
  { value: "docker", label: "Docker Containers" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "jenkins", label: "Jenkins" },
  { value: "python", label: "Python Programming" },
  { value: "javascript", label: "JavaScript Programming" },
  { value: "java", label: "Java Programming" },
  { value: "cpp", label: "C++ Programming" },
  { value: "csharp", label: "C# Programming" },
  { value: "ruby", label: "Ruby Programming" },
  { value: "php", label: "PHP Programming" },
  { value: "swift", label: "Swift Programming" },
  { value: "kotlin", label: "Kotlin Programming" },
  { value: "rust", label: "Rust Programming" },
  { value: "go", label: "Go Programming" },
  { value: "scala", label: "Scala Programming" },
  { value: "typescript", label: "TypeScript Programming" },
  { value: "react", label: "React Framework" },
  { value: "angular", label: "Angular Framework" },
  { value: "vue", label: "Vue.js Framework" },
  { value: "django", label: "Django Framework" },
  { value: "flask", label: "Flask Framework" },
  { value: "spring", label: "Spring Framework" },
  { value: "nodejs", label: "Node.js Runtime" },
  { value: "express", label: "Express.js Framework" },
  { value: "mongodb", label: "MongoDB Database" },
  { value: "mysql", label: "MySQL Database" },
  { value: "postgresql", label: "PostgreSQL Database" },
  { value: "sqlite", label: "SQLite Database" },
  { value: "redis", label: "Redis Database" },
  { value: "apache", label: "Apache Server" },
  { value: "nginx", label: "Nginx Server" },
  { value: "aws", label: "Amazon Web Services (AWS)" },
  { value: "azure", label: "Microsoft Azure" },
  { value: "gcp", label: "Google Cloud Platform (GCP)" },
  { value: "firebase", label: "Firebase Platform" },
  { value: "heroku", label: "Heroku Platform" },
  { value: "digitalocean", label: "DigitalOcean Platform" },
  { value: "linux", label: "Linux Operating System" },
  { value: "windows", label: "Microsoft Windows Operating System" },
  { value: "macos", label: "macOS Operating System" },
  { value: "bash", label: "Bash Scripting" },
  { value: "powershell", label: "PowerShell Scripting" },
  { value: "ansible", label: "Ansible Automation" },
  { value: "terraform", label: "Terraform Infrastructure as Code (IaC)" },
  { value: "kubernetes", label: "Kubernetes Orchestration" },
  { value: "containerization", label: "Containerization Technologies" },
  { value: "microservices", label: "Microservices Architecture" },
  { value: "serverless", label: "Serverless Computing" },
  { value: "graphql", label: "GraphQL" },
  { value: "rest", label: "RESTful APIs" },
  { value: "soap", label: "SOAP APIs" },
  { value: "oauth", label: "OAuth Authentication" },
  { value: "jwt", label: "JSON Web Tokens (JWT)" },
  



]

export const CGPA=[
    { value: "10", label: "10.0" },
    { value: "9.9", label: "9.9" },
    { value: "9.8", label: "9.8" },
    { value: "9.7", label: "9.7" },
    { value: "9.6", label: "9.6" },
    { value: "9.5", label: "9.5" },
    { value: "9.4", label: "9.4" },
    { value: "9.3", label: "9.3" },
    { value: "9.2", label: "9.2" },
    { value: "9.1", label: "9.1" },
    { value: "9.0", label: "9.0" },
    { value: "8.9", label: "8.9" },
    { value: "8.8", label: "8.8" },
    { value: "8.7", label: "8.7" },
    { value: "8.6", label: "8.6" },
    { value: "8.5", label: "8.5" },
    { value: "8.4", label: "8.4" },
    { value: "8.3", label: "8.3" },
    { value: "8.2", label: "8.2" },
    { value: "8.1", label: "8.1" },
    { value: "8.0", label: "8.0" },
    { value: "7.9", label: "7.9" },
    { value: "7.8", label: "7.8" },
    { value: "7.7", label: "7.7" },
    { value: "7.6", label: "7.6" },
    { value: "7.5", label: "7.5" },
    { value: "7.4", label: "7.4" },
    { value: "7.3", label: "7.3" },
    { value: "7.2", label: "7.2" },
    { value: "7.1", label: "7.1" },
    { value: "7.0", label: "7.0" },
    { value: "6.9", label: "6.9" },
    { value: "6.8", label: "6.8" },
    { value: "6.7", label: "6.7" },
    { value: "6.6", label: "6.6" },
    { value: "6.5", label: "6.5" },
    { value: "6.4", label: "6.4" },
    { value: "6.3", label: "6.3" },
    { value: "6.2", label: "6.2" },
    { value: "6.1", label: "6.1" },
    { value: "6.0", label: "6.0" },
    { value: "5.9", label: "5.9" },
    { value: "5.8", label: "5.8" },
    { value: "5.7", label: "5.7" },
    { value: "5.6", label: "5.6" },
    { value: "5.5", label: "5.5" },
    { value: "5.4", label: "5.4" },
    { value: "5.3", label: "5.3" },
    { value: "5.2", label: "5.2" },
    { value: "5.1", label: "5.1" },
    { value: "5.0", label: "5.0" },
    { value: "4.9", label: "4.9" },
    { value: "4.8", label: "4.8" },
    { value: "4.7", label: "4.7" },
    { value: "4.6", label: "4.6" },
    { value: "4.5", label: "4.5" },
    { value: "4.4", label: "4.4" },
    { value: "4.3", label: "4.3" },
    { value: "4.2", label: "4.2" },
    { value: "4.1", label: "4.1" },
    { value: "4.0", label: "4.0" },
    { value: "3.9", label: "3.9" },
    { value: "3.8", label: "3.8" },
    { value: "3.7", label: "3.7" },
    { value: "3.6", label: "3.6" },
    { value: "3.5", label: "3.5" },
    { value: "3.4", label: "3.4" },
    { value: "3.3", label: "3.3" },
    { value: "3.2", label: "3.2" },
    { value: "3.1", label: "3.1" },
    { value: "3.0", label: "3.0" },
    { value: "2.9", label: "2.9" },
    { value: "2.8", label: "2.8" },
    { value: "2.7", label: "2.7" },
    { value: "2.6", label: "2.6" },
    { value: "2.5", label: "2.5" },
    { value: "2.4", label: "2.4" },
    { value: "2.3", label: "2.3" },
    { value: "2.2", label: "2.2" },
    { value: "2.1", label: "2.1" },
    { value: "2.0", label: "2.0" },
    { value: "1.9", label: "1.9" },
    { value: "1.8", label: "1.8" },
    { value: "1.7", label: "1.7" },
    { value: "1.6", label: "1.6" },
    { value: "1.5", label: "1.5" },
    { value: "1.4", label: "1.4" },
    { value: "1.3", label: "1.3" },
    { value: "1.2", label: "1.2" },
    { value: "1.1", label: "1.1" },
    { value: "1.0", label: "1.0" },
    { value: "0", label: "In a first Year" },
]

export const Branch=[  { value: "CSE", label: "Computer Science and Engineering" },
{ value: "AI", label: "Artificial Intelligence" },
{ value: "ML", label: "Machine Learning" },
{ value: "CV", label: "Computer Vision" },
{ value: "NLP", label: "Natural Language Processing" },
{ value: "DS", label: "Data Science" },
{ value: "DBMS", label: "Database Management Systems" },
{ value: "SE", label: "Software Engineering" },
{ value: "CN", label: "Computer Networks" },
{ value: "OS", label: "Operating Systems" },
{ value: "CG", label: "Computer Graphics" },
{ value: "HCI", label: "Human-Computer Interaction" },
{ value: "CyberSec", label: "Cyber Security" },
{ value: "ECE", label: "Electronics and Communication Engineering" },
{ value: "ME", label: "Mechanical Engineering" },
{ value: "CE", label: "Civil Engineering" },
{ value: "EE", label: "Electrical Engineering" },
{ value: "IT", label: "Information Technology" },
{ value: "AE", label: "Aerospace Engineering" },
{ value: "CHE", label: "Chemical Engineering" },
{ value: "BT", label: "Biotechnology" },
{ value: "PT", label: "Petroleum Engineering" },
{ value: "EIE", label: "Electronics and Instrumentation Engineering" },
{ value: "MME", label: "Metallurgical and Materials Engineering" },
{ value: "PE", label: "Production Engineering" },
{ value: "IE", label: "Industrial Engineering" },
{ value: "AE", label: "Automobile Engineering" },
{ value: "EEE", label: "Electrical and Electronics Engineering" },]

export const programmingLanguages = [
    { value: "javascript", label: "JavaScript" },
    { value: "python", label: "Python" },
    { value: "java", label: "Java" },
    { value: "csharp", label: "C#" },
    { value: "cplusplus", label: "C++" },
    { value: "php", label: "PHP" },
    { value: "typescript", label: "TypeScript" },
    { value: "ruby", label: "Ruby" },
    { value: "swift", label: "Swift" },
    { value: "go", label: "Go" },
    { value: "rust", label: "Rust" },
    { value: "scala", label: "Scala" },
    { value: "kotlin", label: "Kotlin" },
    { value: "htmlcss", label: "HTML/CSS" },
    { value: "sql", label: "SQL" },
    { value: "bash", label: "Bash/Shell" },
    { value: "r", label: "R" },
    { value: "matlab", label: "MATLAB" },
    { value: "perl", label: "Perl" },
    { value: "assembly", label: "Assembly" },
    { value: "no", label: "Other" },
    // Add more languages as needed
  ];
  export const knowledgeLevels = [
    { value: "beginner", label: "Beginner" },
    { value: "intermediate", label: "Intermediate" },
    { value: "advanced", label: "Advanced" },
  ];
  
  export const interestLevels = [
    { value: "low", label: "Low" },
    { value: "medium", label: "Medium" },
    { value: "high", label: "High" },
  ];
  
  export const practiceTimes = [
    { value: "none", label: "None" },
    { value: "lessThan1Month", label: "Less than 1 month" },
    { value: "1To3Months", label: "1 to 3 months" },
    { value: "3To6Months", label: "3 to 6 months" },
    { value: "moreThan6Months", label: "More than 6 months" },
  ];
  
  export const learningStyles = [
    { value: "videos", label: "Videos" },
    { value: "books", label: "Books" },
    { value: "tutorials", label: "Tutorials" },
    { value: "classroom", label: "Classroom lectures" },
  ];
  
  export const topicInterest = [
    { value: "low", label: "Low" },
    { value: "medium", label: "Medium" },
    { value: "high", label: "High" },
  ];
  
  export const difficultyLevels = [
    { value: "easy", label: "Easy" },
    { value: "medium", label: "Medium" },
    { value: "hard", label: "Hard" },
  ];
  export const priorExperienceOptions = [
    { value: "beginner", label: "Beginner" },
    { value: "intermediate", label: "Intermediate" },
    { value: "advanced", label: "Advanced" },
  ];  